- hosts: 127.0.0.1
  connection: local

  tasks:
      # Here we conditionally include a list of tasks.
      #
      # The obvious expectation is that this list will be included if the condition is met...
      #
      # But actually Ansible checks the condition for each task in the list.
      - include: tasks_block.yml
        when: true

# Below we include a playbook.
#
# It's a little bit implicitly, besides the fact that we don't specify target hosts before this inclusion
# (which is a signal that we include a playbook, not a list of tasks).
#
- include: separate_playbook.yml
